version: '3'

networks:
  myfabric-network:

services:

  rca-org1:
    container_name: rca-org1
    image: hyperledger/fabric-ca:1.4.0
    command: /bin/bash -c '/scripts/start-root-ca.sh 2>&1 | tee /data/logs/rca-org1.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org1
      - FABRIC_CA_SERVER_DEBUG=true
      #- BOOTSTRAP_USER_PASS=rca-org1-admin:rca-org1-adminpw
      - TARGET_CERTFILE=/data/org1-ca-cert.pem
    volumes:
      - ../scripts:/scripts
      - ./data:/data
      - ./config:/config
    networks:
      - myfabric-network

  ica-org1:
    container_name: ica-org1
    image: hyperledger/fabric-ca:1.4.0
    command: /bin/bash -c '/scripts/start-intermediate-ca.sh 2>&1 | tee /data/logs/ica-org1.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_INTERMEDIATE_TLS_CERTFILES=/data/org1-ca-cert.pem
      - FABRIC_CA_SERVER_CA_NAME=ica-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=ica-org1
      - FABRIC_CA_SERVER_DEBUG=true
      #- BOOTSTRAP_USER_PASS=ica-org1-admin:ica-org1-adminpw
      - PARENT_URL=https://rca-org1-admin:rca-org1-adminpw@rca-org1:7054
      - TARGET_CHAINFILE=/data/org1-ca-chain.pem
    volumes:
      - ../scripts:/scripts
      - ./data:/data
      - ./config:/config
    networks:
      - myfabric-network
    depends_on:
      - rca-org1

  setup-org1:
    container_name: setup-org1
    image: hyperledger/fabric-ca-tools
    command: /bin/bash -c '/scripts/setup-org.sh 2>&1 | tee /data/logs/setup-org1.log; sleep 99999'
    environment:
      - ORG=org1
      - ICA_ADMIN_HOME=/root/cas
      - ICA_FILE=/data/org1-ca-chain.pem
      - ICA_USER_PASS=ica-org1-admin:ica-org1-adminpw
      - ICA_HOST=ica-org1
      - ADMIN_NAME=admin-org1
      - ADMIN_PASS=admin-org1pw
      - ORG_MSP_DIR=/data/msp
      - ORG_ADMIN_HOME=/data/admin
      - PEER_HOMES=/data/peer/peer1 /data/peer/peer2
      - PEER_NAMES=peer1-org1 peer2-org1
      - PEER_PASSES=peer1-org1pw peer2-org1pw
      - PEER_HOSTS=peer1-org1 peer2-org1
      - ORG_USER_HOME=/data/user
      - USER_NAME=user-org1
      - USER_PASS=user-org1pw
    volumes:
      - ../scripts:/scripts
      - ./data:/data
    networks:
      - myfabric-network
    depends_on:
      - ica-org1

